# parameters
RESOLUTION = (1296, 736)
FRAMERATE = 30

HISTORY = 5
MOG2_THRESHOLD = 11
KNN_THRESHOLD = 500

MASK_NOISE_BLUR_RAD = 9

MICROBE_MIN_HEIGHT = 30
MICROBE_MAX_HEIGHT = 40
MICROBE_MIN_AMOUNT = 10
MICROBE_MAX_AMOUNT = 15

OPACITY_DECR = .05
OPACITY_DECR_ODD = .01

MOTION_MAX_DIST = 50
MOTION_MAX_RAND_OFFSET = 2

MIN_DETECTION_CONFIDENCE = .7
MIN_TRACKING_CONFIDENCE = .5

HAND_LABELS = ("Left", "Right")